DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['/kitchen/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot']
ERROR: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:extend_recipe_sysroot(d)
     0003:
File: '/kitchen/meta/classes-global/staging.bbclass', lineno: 619, function: extend_recipe_sysroot
     0615:                    if "/bin/" in l or "/sbin/" in l:
     0616:                        # defer /*bin/* files until last in case they need libs
     0617:                        binfiles[l] = (targetdir, dest)
     0618:                    else:
 *** 0619:                        staging_copyfile(l, targetdir, dest, postinsts, seendirs)
     0620:
     0621:    # Handle deferred binfiles
     0622:    for l in binfiles:
     0623:        (targetdir, dest) = binfiles[l]
File: '/kitchen/meta/classes-global/staging.bbclass', lineno: 165, function: staging_copyfile
     0161:        os.symlink(linkto, dest)
     0162:        #bb.warn(c)
     0163:    else:
     0164:        try:
 *** 0165:            os.link(c, dest)
     0166:        except OSError as err:
     0167:            if err.errno == errno.EXDEV:
     0168:                bb.utils.copyfile(c, dest)
     0169:            else:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/kitchen/build/tmp/sysroots-components/x86_64/quilt-native/etc/quiltrc' -> '/kitchen/build/tmp/work/x86_64-linux/popt-native/1.19/recipe-sysroot-native/etc/quiltrc'

DEBUG: Python function extend_recipe_sysroot finished
